#!/usr/bin/env node
/**
 * Builds data/logos.json: the exact CFBD school string to a logo and the two
 * team colours.
 *
 * This is the one script in the repo that is run by hand and almost never. The
 * map changes when a school rebrands or joins FBS, which is a handful of rows
 * a year, so the file is committed to `main` alongside the code rather than
 * regenerated by the Action. That is deliberate: a logo is not data about the
 * season, and putting it on the 10-minute cron would spend a metered call
 * every run to learn that Iowa's logo is still Iowa's logo.
 *
 *   npm run logos            # CFBD, needs a key, authoritative
 *   npm run logos -- --espn  # ESPN, needs nothing, the fallback
 *
 * WHY CFBD IS THE AUTHORITATIVE SOURCE. `data/rosters.json` joins on the CFBD
 * `school` string with exact equality and never a substring, because `Miami`
 * and `Miami (OH)` are two teams, so are `Ohio` and `Ohio State`, and
 * `Louisiana` is not Louisiana Monroe or Louisiana Tech. CFBD's /teams gives
 * those strings by definition: keying the map on them cannot drift from the
 * thing it joins to, because it is the same field from the same feed.
 *
 * WHY THERE IS AN ESPN PATH AT ALL. The committed file was seeded by it,
 * because the key lives in a gitignored .env that the machine which wrote this
 * did not have. It is sound rather than a shortcut: phase 2 established, and
 * `lib/lines.mjs` depends on daily, that a scoreboard competitor's
 * `team.location` is the CFBD school string verbatim - it is what names the
 * favourite on every spread the page renders. This script reuses that same
 * field, and verifies the result the same way, by asserting that all eighty
 * rostered schools resolve. What ESPN cannot give is a school that has not
 * appeared in a game yet, so the coverage report below is the honest limit and
 * the CFBD run is what closes it.
 *
 * WHY THE DARK LOGO. The page is #0D1520. ESPN publishes a `500-dark` variant
 * beside every `500` one and serves the default bytes where no true dark
 * version exists, so the dark URL is better or identical, never worse. All 186
 * were checked to return 200 before this was chosen.
 *
 * The file is merged, not replaced, unless `--replace` says otherwise. A CFBD
 * run covers FBS; the ESPN seed also picked up the FCS teams that turned up as
 * opponents, and those name real rows in Games of the week. Replacing would
 * throw them away for no reason.
 *
 * Env: CFBD_API_KEY (required unless --espn or --fixture)
 * Usage: node scripts/build-logos.mjs [--espn] [--dry] [--replace]
 *                                     [--out path.json] [--fixture path.json]
 *                                     [--since YYYYMMDD] [--until YYYYMMDD]
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ROSTERS = resolve(ROOT, "data/rosters.json");
const CFBD_API = "https://api.collegefootballdata.com/teams";
const ESPN_API = "https://site.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard";

/* groups=80 is FBS. Without it the scoreboard is every division at once, which
   is not wrong here - an FCS opponent still appears in a game row and still
   wants a logo - but it is thousands of teams no roster will ever name. */
const ESPN_GROUP = "80";

const args = process.argv.slice(2);
const DRY = args.includes("--dry");
const ESPN = args.includes("--espn");
const REPLACE = args.includes("--replace");

const flagValue = (name) => {
  const i = args.indexOf(name);
  if (i === -1) return null;
  const v = args[i + 1];
  if (!v || v.startsWith("--")) {
    console.error(`${name} needs a value.`);
    process.exit(1);
  }
  return v;
};

const OUT = resolve(ROOT, flagValue("--out") ?? "data/logos.json");

/* A captured payload, used instead of the network. This is what makes the test
   suite hermetic - it needs no key and reaches nothing - and it is also how a
   human replays a response that produced a surprising file. Its shape follows
   whichever source was asked for. */
const FIXTURE = flagValue("--fixture");

const doc = JSON.parse(readFileSync(ROSTERS, "utf8"));
const season = doc.season;
const rostered = Object.values(doc.managers).flatMap((r) => r.map((t) => t.cfbd));

/* ------------------------------------------------------------------ */
/* normalising one team, from either feed                              */
/* ------------------------------------------------------------------ */

/** `#00274C`, `00274c`, `#00274c` all become `#00274c`; anything else, null. */
const hex = (value) => {
  if (typeof value !== "string") return null;
  const m = value.trim().replace(/^#/, "");
  return /^[0-9a-fA-F]{6}$/.test(m) ? `#${m.toLowerCase()}` : null;
};

/* ESPN serves the plain URL over http from CFBD and https from its own API.
   The site is https, so an http logo is blocked as mixed content and renders
   as nothing at all - which is a silent failure, and the one failure mode this
   phase is supposed to make impossible. */
const dark = (url) => {
  if (typeof url !== "string" || !url) return null;
  const https = url.replace(/^http:\/\//, "https://");
  return https.includes("/500-dark/") ? https : https.replace("/500/", "/500-dark/");
};

/**
 * CFBD /teams entry to a map row. CFBD has renamed these fields across API
 * versions - `alt_color` became `alternateColor` - so both spellings are read
 * rather than one being guessed at.
 */
const fromCfbd = (t) => {
  const school = t?.school ?? t?.School;
  if (typeof school !== "string" || !school.trim()) return null;
  const logos = Array.isArray(t?.logos) ? t.logos : [];
  const logo = dark(logos.find((l) => typeof l === "string" && l.includes("/500-dark/")) ?? logos[0]);
  if (!logo) return null;
  return [
    school,
    {
      logo,
      color: hex(t?.color ?? t?.Color),
      altColor: hex(t?.alternateColor ?? t?.alt_color ?? t?.altColor),
    },
  ];
};

/**
 * One scoreboard competitor to a map row.
 *
 * `team.location` and not `displayName`, `shortDisplayName` or `abbreviation`.
 * Those are "Miami Hurricanes", "Miami" and "MIA"; only `location` is the CFBD
 * school string, and `lib/lines.mjs` has been joining on it since phase 2.
 */
const fromEspn = (competitor) => {
  const t = competitor?.team;
  const school = t?.location;
  if (typeof school !== "string" || !school.trim()) return null;
  const logo = dark(t?.logo);
  if (!logo) return null;
  return [school, { logo, color: hex(t?.color), altColor: hex(t?.alternateColor) }];
};

/* ------------------------------------------------------------------ */
/* the two feeds                                                       */
/* ------------------------------------------------------------------ */

const readFixture = () => {
  try {
    return JSON.parse(readFileSync(resolve(ROOT, FIXTURE), "utf8"));
  } catch (e) {
    console.error(`--fixture ${FIXTURE}: ${e.message}`);
    process.exit(1);
  }
};

async function fetchJson(url, init) {
  const res = await fetch(url, init);
  if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
  return res.json();
}

async function fromCfbdFeed() {
  const payload = FIXTURE ? readFixture() : await cfbdTeams();
  const teams = Array.isArray(payload) ? payload : payload?.teams;
  if (!Array.isArray(teams)) {
    console.error("CFBD /teams did not return an array. Nothing written.");
    process.exit(1);
  }
  return teams.map(fromCfbd).filter(Boolean);
}

async function cfbdTeams() {
  /* Fail the way verify-teams.mjs fails: one sentence naming the variable, and
     a non-zero exit. This is a hand-run script, so the reader is a person at a
     terminal who needs to be told what to do next and nothing else. */
  const key = process.env.CFBD_API_KEY;
  if (!key) {
    console.error("CFBD_API_KEY is not set.");
    console.error("Put it in .env (see .env.example), or run with --espn to use the free feed.");
    process.exit(1);
  }
  try {
    return await fetchJson(`${CFBD_API}?year=${season}`, {
      headers: { Authorization: `Bearer ${key}` },
    });
  } catch (e) {
    console.error(`CFBD /teams failed: ${e.message}`);
    process.exit(1);
  }
}

/** The Eastern calendar day, which is the only day ESPN's `dates` understands. */
const easternDay = (d) =>
  new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/New_York", year: "numeric", month: "2-digit", day: "2-digit",
  }).format(d).replaceAll("-", "");

async function fromEspnFeed() {
  /* A season-to-date range in one request. ESPN accepts `dates=A-B` and
     answers with every event in it, so seeding the whole map costs a single
     call rather than one per Saturday. */
  const since = flagValue("--since") ?? `${season}0820`;
  const until = flagValue("--until") ?? easternDay(new Date());
  const url = `${ESPN_API}?dates=${since}-${until}&groups=${ESPN_GROUP}&limit=1000`;

  let payload;
  if (FIXTURE) payload = readFixture();
  else {
    try {
      payload = await fetchJson(url);
    } catch (e) {
      console.error(`ESPN scoreboard failed: ${e.message}`);
      process.exit(1);
    }
  }

  const events = Array.isArray(payload?.events) ? payload.events : [];
  if (!events.length) {
    console.error(`ESPN returned no events for ${since}-${until}. Nothing written.`);
    process.exit(1);
  }

  const rows = [];
  for (const ev of events) {
    for (const c of ev?.competitions?.[0]?.competitors ?? []) {
      const row = fromEspn(c);
      if (row) rows.push(row);
    }
  }
  console.log(`ESPN ${since}-${until}: ${events.length} events`);
  return rows;
}

/* ------------------------------------------------------------------ */
/* merge, report, write                                                */
/* ------------------------------------------------------------------ */

function loadStored() {
  if (REPLACE || !existsSync(OUT)) return {};
  try {
    return JSON.parse(readFileSync(OUT, "utf8"))?.teams ?? {};
  } catch (e) {
    console.error(`${OUT} exists but will not parse: ${e.message}`);
    console.error("Refusing to overwrite it. Inspect or delete the file, then re-run.");
    process.exit(1);
  }
}

const source = ESPN ? "espn" : "cfbd";
const rows = ESPN ? await fromEspnFeed() : await fromCfbdFeed();

const teams = loadStored();
let added = 0, changed = 0;
for (const [school, entry] of rows) {
  const before = teams[school];
  if (!before) added++;
  else if (JSON.stringify(before) !== JSON.stringify(entry)) changed++;
  teams[school] = entry;
}

/* Sorted, because this file is read in diffs far more often than it is read in
   full, and an unsorted map turns a two-team change into a whole-file one.
   localeCompare and not the default sort: `San José State` and `Hawai'i` sort
   into nonsense by code point. */
const sorted = Object.fromEntries(
  Object.keys(teams).sort((a, b) => a.localeCompare(b, "en")).map((k) => [k, teams[k]])
);

/* The coverage report is the point of running this by hand. A map that lost
   half the league would look perfect in a screenshot of the half it kept, so
   the run says out loud which of the eighty drafted schools it cannot draw. */
const gaps = rostered.filter((s) => !sorted[s]);
const colourless = rostered.filter((s) => sorted[s] && (!sorted[s].color || !sorted[s].altColor));

console.log(`source ${source}, season ${season}`);
console.log(`${Object.keys(sorted).length} teams in the map (${added} new, ${changed} changed)`);
console.log(`${rostered.length - gaps.length}/${rostered.length} rostered schools resolve`);
if (colourless.length) console.log(`no colours for: ${colourless.join(", ")}`);

if (gaps.length) {
  console.error("");
  console.error(`No logo for ${gaps.length} rostered school(s):`);
  for (const g of gaps) console.error(`  "${g}"`);
  console.error("");
  console.error("These join on exact equality, so a near miss is a miss. Check the string");
  console.error("in data/rosters.json against the feed before assuming the feed is wrong.");
  process.exit(1);
}

const out = {
  $comment:
    "School logos and colours, keyed on the exact CFBD school string that data/rosters.json joins on. Built by scripts/build-logos.mjs and committed by hand; it changes only when a school rebrands or joins FBS. Never substring match a key.",
  season,
  source,
  generatedAt: new Date().toISOString(),
  teams: sorted,
};

if (DRY) {
  console.log(`\n--dry, so ${OUT} was not written.`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, `${JSON.stringify(out, null, 2)}\n`);
  console.log(`\nWrote ${OUT}`);
}
